name: Maven Release
'on':
  release:
    types: [ published ]
jobs:
  zip:
    name: Zip and Upload Shader
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Zip Shader
        uses: vimtor/action-zip@v1.2
        with:
          files: shaders
          dest: "Nwoofs-Wynn-Shader-${{ github.event.release.tag_name }}.zip"
      # An optional step to also upload the `.jar` to the GitHub release assets
      - name: Upload to Release
        uses: JasonEtco/upload-to-release@v0.1.1
        with:
          args: Nwoofs-Wynn-Shader-${{ github.event.release.tag_name }}.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      # Upload the .jar to Modrinth
      - name: Upload to Modrinth
        uses: cloudnode-pro/modrinth-publish@1.0.0
        with:
          token: '${{ secrets.MODRINTH_TOKEN }}' # You need to create this secret in your repository settings
          project: K8XDv70D # Replace with your project id/slug
          file: "Nwoofs-Wynn-Shader-${{ github.event.release.tag_name }}.zip" # Make sure that this matches the file name of your .jar
          changelog: '${{ github.event.release.body }}' # Copies the version changelog from the GitHub release notes
          loaders: 'iris' # A list of your supported loaders
