name: Maven Release
'on':
  release:
    types: [ published ]
jobs:
  zip:
    name: Zip and Upload Shader
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Zip Shader
        uses: vimtor/action-zip@v1.2
        with:
          files: shaders
          dest: "Nwoofs-Wynn-Shader-${{ github.event.release.tag_name }}.zip"
      # An optional step to also upload the `.jar` to the GitHub release assets
      - name: Upload to Release
        uses: JasonEtco/upload-to-release@v0.1.1
        with:
          args: Nwoofs-Wynn-Shader-${{ github.event.release.tag_name }}.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      # Upload the .jar to Modrinth
      - name: Upload to Modrinth
        uses: dsx137/modrinth-release-action@main
        env:
            MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        with:
            name: Nwoofs-Wynn-Shader-${{ github.event.release.tag_name }}.zip
            project_id: K8XDv70D
            loaders: iris
            game_versions: 1.21:1.21.1
            version_number: ${{ github.event.release.tag_name }}
            files: |
                ./shaders/*
            dependencies: YL57xq9U:required, uCdwusMi:optional
            changelog: "${{ github.event.release.body }}"
            version_type: alpha # or beta, alpha
            featured: false
            status: 'listed' # or archived, draft, unlisted, scheduled, unknown
            requested_status: 'listed' # or archived, draft, unlisted
            updatable: false # default true, means updating existing version
            delete_old_files: false # default true
