name: Maven Release
'on':
  release:
    types: [ published ]
jobs:
  zip:
    name: Zip and Upload Shader
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Zip Shader
        uses: vimtor/action-zip@v1.2
        with:
          files: ./
          dest: "Nwoofs-Wynn-Shader-${{ github.event.release.tag_name }}.zip"
          args: -x "./.git" "./.github"
      # An optional step to also upload the `.jar` to the GitHub release assets
      - name: Upload to Release
        uses: JasonEtco/upload-to-release@v0.1.1
        with:
          args: Nwoofs-Wynn-Shader-${{ github.event.release.tag_name }}.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
